image: dockslim/dotnet-gcc-cmake:bionic
manifests:
  - image: dockslim/dotnet-gcc-cmake:bionic-amd64
    platform:
      architecture: amd64
      os: linux
  - image: dockslim/dotnet-gcc-cmake:bionic-arm32v7
    platform:
      architecture: arm
      os: linux
      variant: v7
  - image: dockslim/dotnet-gcc-cmake:bionic-arm64v8
    platform:
      architecture: arm64
      os: linux
      variant: v8
